// Path to tools used by the JAFFA pipeline
bpipe="bpipe"
velveth="velveth"
velvetg="velvetg"
oases="oases"
trimmomatic="java -jar /usr/share/java/trimmomatic.jar \$@"
samtools="samtools"
bowtie2="bowtie2"
blat="blat"
dedupe="/opt/bbmap/dedupe.sh \$@"
reformat="/opt/bbmap/reformat.sh \$@"
R="R"
