// make_final_table.cpp
// Standalone C++11 (STL only) port of make_final_table.R
//
// Build:
//   g++ -std=c++11 -O2 -o make_final_table make_final_table.cpp
//
// Run (same argument order as R):
//   ./make_final_table <blat.psl> <fusion_info.reads> <gene_counts> <trans_table>
//                      <mitelman> <cosmic> <cosmic_tier> <gtex>
//                      <gapmin> <exclude_csv> <MIN_REASSIGNMENT_BASE_DIFF> <output>
//
// Notes:
// - Assumes tab-delimited inputs like the R script.
// - PSL is expected to be standard 21-column BLAT PSL (no header).
// - The annotation table is expected to have columns used by the R script:
//     chrom, txStart, txEnd, exonStarts, exonEnds, exonFrames, name2, strand, (and possibly chromStart/chromEnd).
//   If txStart/txEnd missing, chromStart/chromEnd will be used (like R).
//
// This is a faithful port, not a re-design.
// NOTE/WARNING: This code was generated by AI (ChatGPT) as a port from the R
// equivalent (make_final_table.R) in 2026 by Nadia Davidson.
// Code was thoroughly tested, but there may be difference

#include <algorithm>
#include <cassert>
#include <cmath>
#include <cstddef>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <limits>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

static const int OVERHANG_MAX = 20;
static const int REGGAP = 200;              // kb
static const int TRAN_GAP_MAX = 30;         // bp
static const int MIN_LOW_SPANNING_READS = 2;

static const bool REMOVE_ALT = true;
static const bool REMOVE_CHRM = true;

static inline bool is_nan_double(double x) {
  return std::isnan(x);
}

static inline std::vector<std::string> split(const std::string& s, char delim, bool keep_empty = false) {
  std::vector<std::string> out;
  std::string cur;
  for (size_t i = 0; i < s.size(); ++i) {
    char c = s[i];
    if (c == delim) {
      if (keep_empty || !cur.empty()) out.push_back(cur);
      cur.clear();
    } else {
      cur.push_back(c);
    }
  }
  if (keep_empty || !cur.empty()) out.push_back(cur);
  return out;
}

static inline std::string trim_crlf(std::string s) {
  while (!s.empty() && (s.back() == '\r' || s.back() == '\n')) s.pop_back();
  return s;
}

static inline long long to_ll(const std::string& s, long long def = 0) {
  if (s.empty()) return def;
  char* end = NULL;
  long long v = std::strtoll(s.c_str(), &end, 10);
  if (end == s.c_str()) return def;
  return v;
}

static inline double to_double(const std::string& s, double def = 0.0) {
  if (s.empty()) return def;
  char* end = NULL;
  double v = std::strtod(s.c_str(), &end);
  if (end == s.c_str()) return def;
  return v;
}

static inline bool contains(const std::string& s, const std::string& pat) {
  return s.find(pat) != std::string::npos;
}

static inline std::vector<int> split_ints_csv(const std::string& s) {
  std::vector<int> out;
  std::vector<std::string> toks = split(s, ',', true);
  for (size_t i = 0; i < toks.size(); ++i) {
    if (toks[i].empty()) continue;
    out.push_back(static_cast<int>(to_ll(toks[i], 0)));
  }
  return out;
}

static inline std::vector<int> split_ints_csv_plus1(const std::string& s) {
  std::vector<int> out = split_ints_csv(s);
  for (size_t i = 0; i < out.size(); ++i) out[i] += 1;
  return out;
}

struct FusionInfoRow {
  std::string transcript;
  std::string spanning_pairs_raw; // "-" or numeric
  long long spanning_reads = 0;
  long long break_min = 0;
  long long break_max = 0;
};

struct BlatPslRow {
  // PSL fields (0-based index)
  // 0 matches, 1 misMatches, ... 8 strand, 9 qName, 10 qSize, 11 qStart, 12 qEnd,
  // 13 tName, 14 tSize, 15 tStart, 16 tEnd, 17 blockCount, 18 blockSizes, 19 qStarts, 20 tStarts
  long long matches = 0;
  long long misMatches = 0;
  std::string strand; // "+" or "-"
  std::string qName;
  long long qSize = 0;
  long long qStart = 0;
  long long qEnd = 0;
  std::string tName;  // chrom
  // pre-parsed lists:
  std::vector<int> blockSizes;
  std::vector<int> qStarts;
  std::vector<int> tStarts;
};

struct AnnoRow {
  std::string chrom;
  long long txStart = 0;
  long long txEnd = 0;
  std::string exonStarts;  // csv
  std::string exonEnds;    // csv
  std::string exonFrames;  // csv
  std::string name2;       // gene symbol
  std::string strand;      // "+" or "-"
};

struct BreakHit {
  std::string genome_chrom;
  long long genome_pos = 0;
  bool genome_dir = true;   // + strand in PSL
  bool is_start = true;     // which contig breakpoint side
  long long brk = 0;        // contig break coordinate
  long long length = 0;     // matches
  double pid = 0.0;         // 1 - misMatches/matches

  // from later steps:
  long long gap_kb_as_ll = 0; // stored only for the 2-row chosen pair
  double gap = std::numeric_limits<double>::infinity(); // kb
  bool rearrangement = false;

  long long overhang = 0;
  int frame = -1;
  bool is_actually_the_start = false;
  std::string gene_name;
  std::string exons;

  bool aligns = false;
  bool inFrame = false;
};

struct FinalRow {
  // Fusion info
  std::string transcript;
  std::string spanning_pairs; // "-" or numeric string
  long long spanning_reads = 0;

  // Genome info
  long long contig_break = 0;
  std::string chrom1;
  long long base1 = 0;
  std::string strand1;
  std::string chrom2;
  long long base2 = 0;
  std::string strand2;

  double gap = std::numeric_limits<double>::quiet_NaN();
  bool rearrangement = false;
  bool aligns = false;
  bool inframe = false;
  std::string fusion_genes;
  std::string exon1;
  std::string exon2;

  // DB annotations
  std::string known_mitelman = "-";
  std::string known_cosmic = "-";
  std::string cosmic_tier = "-";
  long long gtex_samples = 0;

  // Gene-level counts
  double geneCounts1 = 0.0;
  double geneCounts2 = 0.0;

  // Classification
  std::string classification = "NoSupport";
};

static bool read_line(std::ifstream& in, std::string& line) {
  if (!std::getline(in, line)) return false;
  line = trim_crlf(line);
  return true;
}

static std::vector<std::string> split_tsv(const std::string& line) {
  return split(line, '\t', true);
}

static std::vector<FusionInfoRow> read_fusion_info(const std::string& path) {
  std::ifstream in(path.c_str());
  if (!in) {
    throw std::runtime_error("Failed to open fusion_info_file: " + path);
  }
  std::string header;
  if (!read_line(in, header)) return {};

  std::vector<std::string> cols = split_tsv(header);
  std::unordered_map<std::string, int> col_i;
  for (size_t i = 0; i < cols.size(); ++i) col_i[cols[i]] = (int)i;

  auto idx = [&](const std::string& name) -> int {
    std::unordered_map<std::string,int>::const_iterator it = col_i.find(name);
    if (it == col_i.end()) return -1;
    return it->second;
  };

  int i_transcript = idx("transcript");
  int i_sp_pairs = idx("spanning_pairs");
  int i_sp_reads = idx("spanning_reads");
  int i_break_min = idx("break_min");
  int i_break_max = idx("break_max");

  if (i_transcript < 0 || i_sp_pairs < 0 || i_sp_reads < 0 || i_break_min < 0 || i_break_max < 0) {
    throw std::runtime_error("fusion_info file missing required columns.");
  }

  std::vector<FusionInfoRow> out;
  std::string line;
  while (read_line(in, line)) {
    if (line.empty()) continue;
    std::vector<std::string> f = split_tsv(line);
    if ((int)f.size() <= std::max(std::max(i_transcript, i_sp_pairs), std::max(i_break_min, i_break_max))) continue;

    FusionInfoRow r;
    r.transcript = f[i_transcript];
    r.spanning_pairs_raw = f[i_sp_pairs];
    r.spanning_reads = to_ll(f[i_sp_reads], 0);
    r.break_min = to_ll(f[i_break_min], 0);
    r.break_max = to_ll(f[i_break_max], 0);
    out.push_back(r);
  }
  return out;
}


static std::vector<AnnoRow> read_annotation_table(const std::string& path) {
  std::ifstream in(path.c_str());
  if (!in) throw std::runtime_error("Failed to open trans_table_file: " + path);

  std::string header;
  if (!read_line(in, header)) return {};

  std::vector<std::string> cols = split_tsv(header);
  for (auto& c : cols) {
    if (!c.empty() && c[0] == '#') c = c.substr(1);
  }

  std::unordered_map<std::string,int> col;
  for (size_t i = 0; i < cols.size(); ++i) col[cols[i]] = (int)i;

  auto has = [&](const std::string& s){ return col.count(s); };
  auto idx = [&](const std::string& s){ return col.count(s) ? col[s] : -1; };

  // ---- T2T compatibility: rename chromStart/chromEnd → txStart/txEnd ----
  if (!has("txStart") && has("chromStart")) col["txStart"] = col["chromStart"];
  if (!has("txEnd")   && has("chromEnd"))   col["txEnd"]   = col["chromEnd"];

  if (!has("txStart") || !has("txEnd"))
    throw std::runtime_error("Annotation missing txStart/txEnd (or chromStart/chromEnd)");

  bool has_exonEnds   = has("exonEnds");
  bool has_exonStarts = has("exonStarts");

  bool is_T2T = !has_exonEnds;

  if (is_T2T) {
    if (!has("chromStarts") || !has("blockSizes"))
      throw std::runtime_error("T2T annotation requires chromStarts and blockSizes");
  }

  std::cerr << "[INFO] Reading annotation table";
  if (is_T2T) std::cerr << " (T2T mode detected)";
  std::cerr << "...\n";

  std::vector<AnnoRow> out;
  std::string line;

  while (read_line(in, line)) {
    if (line.empty()) continue;
    auto f = split_tsv(line);

    AnnoRow r;
    r.chrom    = f[idx("chrom")];
    r.txStart  = to_ll(f[idx("txStart")]);
    r.txEnd    = to_ll(f[idx("txEnd")]);
    r.name2    = f[idx("name2")];
    r.strand   = f[idx("strand")];
    r.exonFrames = f[idx("exonFrames")];

    if (!is_T2T) {
      // ---- Standard annotation ----
      r.exonStarts = f[idx("exonStarts")];
      r.exonEnds   = f[idx("exonEnds")];
    } else {
      // ---- T2T exon reconstruction (exact R equivalent) ----
      auto chromStarts = split_ints_csv(f[idx("chromStarts")]);
      auto blockSizes  = split_ints_csv(f[idx("blockSizes")]);

      std::vector<long long> exonStarts;
      std::vector<long long> exonEnds;

      for (size_t i = 0; i < chromStarts.size(); ++i) {
        long long start = r.txStart + chromStarts[i];
        long long end   = start + blockSizes[i];
        exonStarts.push_back(start);
        exonEnds.push_back(end);
      }

      // collapse back to CSV strings (like R's paste(..., collapse=","))
      auto collapse = [](const std::vector<long long>& v){
        std::ostringstream oss;
        for (size_t i = 0; i < v.size(); ++i) {
          if (i) oss << ",";
          oss << v[i];
        }
        return oss.str();
      };

      r.exonStarts = collapse(exonStarts);
      r.exonEnds   = collapse(exonEnds);
    }

    out.push_back(r);
  }

  std::cerr << "[INFO] Loaded " << out.size() << " transcripts\n";
  return out;
}


static std::vector<BlatPslRow> read_psl(const std::string& path) {
  std::ifstream in(path.c_str());
  if (!in) throw std::runtime_error("Failed to open blat_table_file: " + path);

  std::vector<BlatPslRow> out;
  std::string line;
  while (read_line(in, line)) {
    if (line.empty()) continue;
    std::vector<std::string> f = split_tsv(line);
    if (f.size() < 21) continue;

    BlatPslRow r;
    r.matches = to_ll(f[0], 0);
    r.misMatches = to_ll(f[1], 0);
    r.strand = f[8];
    r.qName = f[9];
    r.qSize = to_ll(f[10], 0);
    r.qStart = to_ll(f[11], 0);
    r.qEnd = to_ll(f[12], 0);
    r.tName = f[13];

    r.blockSizes = split_ints_csv(f[18]);
    r.qStarts = split_ints_csv(f[19]);
    r.tStarts = split_ints_csv(f[20]);

    out.push_back(r);
  }
  return out;
}

static std::unordered_map<std::string, std::vector<int> > build_blat_index(const std::vector<BlatPslRow>& psl) {
  std::unordered_map<std::string, std::vector<int> > idx;
  for (size_t i = 0; i < psl.size(); ++i) {
    idx[psl[i].qName].push_back((int)i);
  }
  // remove candidates with 0 or 1 alignments, as per R
  std::vector<std::string> to_erase;
  to_erase.reserve(idx.size());
  for (std::unordered_map<std::string, std::vector<int> >::const_iterator it = idx.begin(); it != idx.end(); ++it) {
    if (it->second.size() <= 1) to_erase.push_back(it->first);
  }
  for (size_t k = 0; k < to_erase.size(); ++k) idx.erase(to_erase[k]);
  return idx;
}

static std::unordered_map<std::string, std::vector<AnnoRow> > split_annotation_by_chr(std::vector<AnnoRow>& anno) {
  std::unordered_map<std::string, std::vector<AnnoRow> > by;
  for (size_t i = 0; i < anno.size(); ++i) {
    by[anno[i].chrom].push_back(anno[i]);
  }
  for (std::unordered_map<std::string, std::vector<AnnoRow> >::iterator it = by.begin(); it != by.end(); ++it) {
    std::vector<AnnoRow>& v = it->second;
    std::sort(v.begin(), v.end(), [](const AnnoRow& a, const AnnoRow& b){
      return a.txStart < b.txStart;
    });
  }
  return by;
}

static std::unordered_map<std::string, std::string> build_gene_to_strand(const std::vector<AnnoRow>& anno) {
  // first occurrence wins (similar to match in R)
  std::unordered_map<std::string, std::string> m;
  for (size_t i = 0; i < anno.size(); ++i) {
    if (m.find(anno[i].name2) == m.end()) m[anno[i].name2] = anno[i].strand;
  }
  return m;
}

static std::vector<BreakHit> get_break_pos_for_transcript(
    const FusionInfoRow& fus,
    const std::vector<BlatPslRow>& blat,
    const std::unordered_map<std::string, std::vector<int> >& blat_index
) {
  std::unordered_map<std::string, std::vector<int> >::const_iterator it = blat_index.find(fus.transcript);
  if (it == blat_index.end()) return std::vector<BreakHit>();

  const std::vector<int>& rows = it->second;
  long long break_in_trans1 = fus.break_min;
  long long break_in_trans2 = fus.break_max;

  auto get_one = [&](int j_local, long long brk, bool is_start) -> bool {
    const BlatPslRow& x = blat[rows[(size_t)j_local]];

    std::vector<int> width = x.blockSizes;
    std::vector<int> start = x.qStarts;
    std::vector<int> genome_starts = x.tStarts;

    // adjust small gaps in transcript alignment
    int l = (int)start.size();
    if (l > 1) {
      for (int k = 0; k < l - 1; ++k) {
        int gap = start[k + 1] - start[k] - width[k];
        if (gap > TRAN_GAP_MAX) gap = 0;
        width[k] += gap;
      }
      // last gap is 0 in R; width last unchanged
    }

    bool genome_dir = (x.strand == "+");
    if (!genome_dir) {
      // reverse qStarts and shift tStarts like R
      // start = qSize - qStarts - width
      for (size_t k = 0; k < start.size(); ++k) {
        start[k] = (int)(x.qSize - start[k] - width[k]);
      }
      for (size_t k = 0; k < genome_starts.size(); ++k) {
        genome_starts[k] += width[k];
      }
    }

    // find block containing brk
    int block_idx = -1;
    for (int k = 0; k < l; ++k) {
      if ((long long)start[k] <= brk && (long long)start[k] + (long long)width[k] >= brk) {
        block_idx = k;
        break;
      }
    }
    if (block_idx < 0) return false;

    long long offset = brk - (long long)start[block_idx];
    long long genome_pos = 0;
    if (genome_dir) {
      genome_pos = (long long)genome_starts[block_idx] + offset;
    } else {
      genome_pos = (long long)genome_starts[block_idx] - offset + 1;
    }

    // magic filters near ends of alignment
    if (is_start && (brk - x.qStart) < 15) return false;
    if (!is_start && (x.qEnd - brk) < 15) return false;

    double pid = 0.0;
    if (x.matches > 0) pid = 1.0 - (double)x.misMatches / (double)x.matches;

    BreakHit hit;
    hit.genome_chrom = x.tName;
    hit.genome_pos = genome_pos;
    hit.genome_dir = genome_dir;
    hit.is_start = is_start;
    hit.brk = brk;
    hit.length = x.matches;
    hit.pid = pid;
    // other fields filled later
    // store temporarily by pushing to a captured vector? We'll return via outer vector.
    // We'll handle push outside by returning true and capturing in a vector in caller.
    return true;
  };

  std::vector<BreakHit> res;
  for (int j = 0; j < (int)rows.size(); ++j) {
    // start side
    {
      const BlatPslRow& x = blat[rows[(size_t)j]];
      // build hit via re-running logic but we need the actual hit values
      std::vector<int> width = x.blockSizes;
      std::vector<int> start = x.qStarts;
      std::vector<int> genome_starts = x.tStarts;
      int l = (int)start.size();
      if (l > 1) {
        for (int k = 0; k < l - 1; ++k) {
          int gap = start[k + 1] - start[k] - width[k];
          if (gap > TRAN_GAP_MAX) gap = 0;
          width[k] += gap;
        }
      }
      bool genome_dir = (x.strand == "+");
      if (!genome_dir) {
        for (size_t k = 0; k < start.size(); ++k) start[k] = (int)(x.qSize - start[k] - width[k]);
        for (size_t k = 0; k < genome_starts.size(); ++k) genome_starts[k] += width[k];
      }
      int block_idx = -1;
      for (int k = 0; k < l; ++k) {
        if ((long long)start[k] <= break_in_trans1 && (long long)start[k] + (long long)width[k] >= break_in_trans1) {
          block_idx = k; break;
        }
      }
      if (block_idx >= 0) {
        if (!((break_in_trans1 - x.qStart) < 15)) {
          long long offset = break_in_trans1 - (long long)start[block_idx];
          long long genome_pos = genome_dir ? (long long)genome_starts[block_idx] + offset
                                            : (long long)genome_starts[block_idx] - offset + 1;
          double pid = (x.matches > 0) ? 1.0 - (double)x.misMatches / (double)x.matches : 0.0;
          BreakHit hit;
          hit.genome_chrom = x.tName;
          hit.genome_pos = genome_pos;
          hit.genome_dir = genome_dir;
          hit.is_start = true;
          hit.brk = break_in_trans1;
          hit.length = x.matches;
          hit.pid = pid;
          res.push_back(hit);
        }
      }
    }
    // end side
    {
      const BlatPslRow& x = blat[rows[(size_t)j]];
      std::vector<int> width = x.blockSizes;
      std::vector<int> start = x.qStarts;
      std::vector<int> genome_starts = x.tStarts;
      int l = (int)start.size();
      if (l > 1) {
        for (int k = 0; k < l - 1; ++k) {
          int gap = start[k + 1] - start[k] - width[k];
          if (gap > TRAN_GAP_MAX) gap = 0;
          width[k] += gap;
        }
      }
      bool genome_dir = (x.strand == "+");
      if (!genome_dir) {
        for (size_t k = 0; k < start.size(); ++k) start[k] = (int)(x.qSize - start[k] - width[k]);
        for (size_t k = 0; k < genome_starts.size(); ++k) genome_starts[k] += width[k];
      }
      int block_idx = -1;
      for (int k = 0; k < l; ++k) {
        if ((long long)start[k] <= break_in_trans2 && (long long)start[k] + (long long)width[k] >= break_in_trans2) {
          block_idx = k; break;
        }
      }
      if (block_idx >= 0) {
        if (!((x.qEnd - break_in_trans2) < 15)) {
          long long offset = break_in_trans2 - (long long)start[block_idx];
          long long genome_pos = genome_dir ? (long long)genome_starts[block_idx] + offset
                                            : (long long)genome_starts[block_idx] - offset + 1;
          double pid = (x.matches > 0) ? 1.0 - (double)x.misMatches / (double)x.matches : 0.0;
          BreakHit hit;
          hit.genome_chrom = x.tName;
          hit.genome_pos = genome_pos;
          hit.genome_dir = genome_dir;
          hit.is_start = false;
          hit.brk = break_in_trans2;
          hit.length = x.matches;
          hit.pid = pid;
          res.push_back(hit);
        }
      }
    }
  }

  return res;
}

static bool rearrangement_of_pair(const BreakHit& a, const BreakHit& b) {
  if (a.genome_chrom != b.genome_chrom) return true;
  if (a.genome_dir != b.genome_dir) return true; // inversion
  // ((endpos > startpos) != dir)
  const BreakHit* start = a.is_start ? &a : &b;
  const BreakHit* end = a.is_start ? &b : &a;
  bool end_gt_start = (end->genome_pos > start->genome_pos);
  if (end_gt_start != a.genome_dir) return true;
  return false;
}

static std::vector<BreakHit> check_gap_choose_pair(const std::vector<BreakHit>& x, long long gapmin_bp) {
  if (x.empty()) return std::vector<BreakHit>();

  bool any_start = false, any_end = false;
  for (size_t i = 0; i < x.size(); ++i) {
    if (x[i].is_start) any_start = true; else any_end = true;
  }
  if (!(any_start && any_end)) return std::vector<BreakHit>();

  std::vector<BreakHit> starts, ends;
  for (size_t i = 0; i < x.size(); ++i) (x[i].is_start ? starts : ends).push_back(x[i]);

  auto get_best_fit = [&]() -> std::vector<BreakHit> {
    // try close start/end < REGGAP*1000, same chrom, same dir
    for (size_t i = 0; i < starts.size(); ++i) {
      for (size_t j = 0; j < ends.size(); ++j) {
        if (starts[i].genome_chrom == ends[j].genome_chrom &&
            starts[i].genome_dir == ends[j].genome_dir) {
          long long d = std::llabs(ends[j].genome_pos - starts[i].genome_pos);
          if (d < (long long)REGGAP * 1000LL) {
            BreakHit a = starts[i];
            BreakHit b = ends[j];
            double gap_kb = (a.genome_chrom == b.genome_chrom) ? (double)std::llabs(b.genome_pos - a.genome_pos) / 1000.0
                                                               : std::numeric_limits<double>::infinity();
            bool r = rearrangement_of_pair(a, b);
            a.gap = gap_kb; b.gap = gap_kb;
            a.rearrangement = r; b.rearrangement = r;
            return std::vector<BreakHit>{a, b};
          }
        }
      }
    }

    // otherwise choose max length*pid for start and end
    auto best_idx = [](const std::vector<BreakHit>& v) -> size_t {
      size_t bi = 0;
      double bv = -1.0;
      for (size_t i = 0; i < v.size(); ++i) {
        double score = (double)v[i].length * v[i].pid;
        if (score > bv) { bv = score; bi = i; }
      }
      return bi;
    };
    BreakHit a = starts[best_idx(starts)];
    BreakHit b = ends[best_idx(ends)];
    double gap_kb = (a.genome_chrom == b.genome_chrom) ? (double)std::llabs(b.genome_pos - a.genome_pos) / 1000.0
                                                       : std::numeric_limits<double>::infinity();
    bool r = rearrangement_of_pair(a, b);
    a.gap = gap_kb; b.gap = gap_kb;
    a.rearrangement = r; b.rearrangement = r;
    return std::vector<BreakHit>{a, b};
  };

  // check if any start/end on same chrom exists
  bool any_same_chrom = false;
  for (size_t i = 0; i < starts.size() && !any_same_chrom; ++i) {
    for (size_t j = 0; j < ends.size(); ++j) {
      if (starts[i].genome_chrom == ends[j].genome_chrom) { any_same_chrom = true; break; }
    }
  }
  if (!any_same_chrom) return get_best_fit();

  // compute minimal distance among start/end pairs on same chrom
  long long best_gap = std::numeric_limits<long long>::max();
  size_t bi = 0, bj = 0;
  bool found = false;
  for (size_t i = 0; i < starts.size(); ++i) {
    for (size_t j = 0; j < ends.size(); ++j) {
      if (starts[i].genome_chrom != ends[j].genome_chrom) continue;
      long long d = std::llabs(ends[j].genome_pos - starts[i].genome_pos);
      if (d < best_gap) { best_gap = d; bi = i; bj = j; found = true; }
    }
  }
  if (!found) return get_best_fit();

  // if gap < gapmin and no rearrangement -> reject
  {
    BreakHit a = starts[bi];
    BreakHit b = ends[bj];
    bool r = rearrangement_of_pair(a, b);
    if (best_gap < gapmin_bp && !r) return std::vector<BreakHit>();
  }

  return get_best_fit();
}

static std::vector<AnnoRow> find_overlapping_annos(
    const std::unordered_map<std::string, std::vector<AnnoRow> >& trans_by_chr,
    const std::string& chrom,
    long long pos
) {
  std::unordered_map<std::string, std::vector<AnnoRow> >::const_iterator it = trans_by_chr.find(chrom);
  if (it == trans_by_chr.end()) return {};
  const std::vector<AnnoRow>& v = it->second;

  // Simple scan; could be binary searched but keep direct parity with R logic
  std::vector<AnnoRow> out;
  for (size_t i = 0; i < v.size(); ++i) {
    if (v[i].txStart <= pos && v[i].txEnd >= pos) out.push_back(v[i]);
  }
  return out;
}

static std::vector<BreakHit> get_frame_info_for_pair(
    const std::vector<BreakHit>& pair2,
    const std::unordered_map<std::string, std::vector<AnnoRow> >& trans_by_chr
) {
  if (pair2.size() != 2) return std::vector<BreakHit>();
  std::vector<BreakHit> res;
  res.reserve(2);

  auto do_one = [&](const BreakHit& row) -> bool {
    std::vector<AnnoRow> genes = find_overlapping_annos(trans_by_chr, row.genome_chrom, row.genome_pos);
    if (genes.empty()) return false;

    // exon positions depend on direction and start/end
    // if genome_dir == is_start => use exonEnds, else exonStarts + 1
    std::vector< std::vector<int> > exon_pos;
    exon_pos.reserve(genes.size());

    if (row.genome_dir == row.is_start) {
      for (size_t i = 0; i < genes.size(); ++i) exon_pos.push_back(split_ints_csv(genes[i].exonEnds));
    } else {
      for (size_t i = 0; i < genes.size(); ++i) exon_pos.push_back(split_ints_csv_plus1(genes[i].exonStarts));
    }

    // find min dist for each transcript
    std::vector<long long> dists(genes.size(), (long long)1e18);
    long long best = (long long)1e18;
    for (size_t i = 0; i < exon_pos.size(); ++i) {
      long long md = (long long)1e18;
      for (size_t k = 0; k < exon_pos[i].size(); ++k) {
        long long d = std::llabs((long long)exon_pos[i][k] - row.genome_pos);
        if (d < md) md = d;
      }
      dists[i] = md;
      if (md < best) best = md;
    }

    std::vector<size_t> best_trans;
    for (size_t i = 0; i < dists.size(); ++i) if (dists[i] == best) best_trans.push_back(i);
    if (best_trans.empty()) return false;

    // Build candidates for each best transcript
    struct Cand { BreakHit hit; };
    std::vector<Cand> cands;

    for (size_t bi = 0; bi < best_trans.size(); ++bi) {
      size_t ti = best_trans[bi];
      const AnnoRow& g = genes[ti];
      const std::vector<int>& ex = exon_pos[ti];

      // closest exon index
      long long best_abs = (long long)1e18;
      size_t closest = 0;
      for (size_t k = 0; k < ex.size(); ++k) {
        long long d = (long long)ex[k] - row.genome_pos;
        long long ad = std::llabs(d);
        if (ad < best_abs) { best_abs = ad; closest = k; }
      }

      long long overhang = (long long)ex[closest] - row.genome_pos;
      bool is_actually_the_start = (((g.strand == "+") == row.genome_dir) == row.is_start);

      std::vector<int> frames = split_ints_csv(g.exonFrames);
      int frame = -1;
      if (closest < frames.size()) frame = frames[closest];

      if (is_actually_the_start && frame >= 0) {
        int dir = (g.strand == "+") ? 1 : -1;
        long long next = (long long)closest + dir;
        if (next < 0 || next >= (long long)frames.size()) {
          frame = -1;
        } else {
          frame = frames[(size_t)next];
        }
      }

      BreakHit out = row;
      out.overhang = overhang;
      out.frame = frame;
      out.is_actually_the_start = is_actually_the_start;
      out.gene_name = g.name2;
      {
        std::ostringstream oss;
        oss << (closest + 1) << "/" << ex.size();
        out.exons = oss.str();
      }
      cands.push_back(Cand{out});
    }

    // choose isoform with most common coding frame (fs!=-1); if none, choose -1
    std::map<int,int> freq;
    for (size_t i = 0; i < cands.size(); ++i) {
      int f = cands[i].hit.frame;
      if (f != -1) freq[f] += 1;
    }
    int chosen = -1;
    if (!freq.empty()) {
      int bestc = -1;
      for (std::map<int,int>::const_iterator it = freq.begin(); it != freq.end(); ++it) {
        if (it->second > bestc) { bestc = it->second; chosen = it->first; }
      }
    }

    size_t pick = 0;
    if (chosen != -1) {
      for (size_t i = 0; i < cands.size(); ++i) {
        if (cands[i].hit.frame == chosen) { pick = i; break; }
      }
    }
    res.push_back(cands[pick].hit);
    return true;
  };

  if (!do_one(pair2[0])) return std::vector<BreakHit>();
  if (!do_one(pair2[1])) return std::vector<BreakHit>();
  if (res.size() != 2) return std::vector<BreakHit>();
  if (res[0].gene_name == res[1].gene_name) return std::vector<BreakHit>(); // reject same-gene halves

  // align/overhang correction + inFrame check
  // dir = +1 unless genome_dir==FALSE => -1
  long long dir0 = res[0].genome_dir ? 1 : -1;
  long long dir1 = res[1].genome_dir ? 1 : -1;

  long long new_break0 = res[0].brk + dir0 * res[0].overhang;
  long long new_break1 = res[1].brk + dir1 * res[1].overhang;

  // identify start vs end in res vector
  int idx_start = res[0].is_start ? 0 : 1;
  int idx_end = res[0].is_start ? 1 : 0;

  bool aligns = false;
  if ((new_break1 - new_break0 == 1 && idx_end == 1 && idx_start == 0) ||
      (new_break0 - new_break1 == 1 && idx_end == 0 && idx_start == 1)) {
    // same condition as R, but we’ll compute using start/end indices:
  }

  long long nb_end = (idx_end == 0) ? new_break0 : new_break1;
  long long nb_start = (idx_start == 0) ? new_break0 : new_break1;

  long long sum_abs_overhang = std::llabs(res[0].overhang) + std::llabs(res[1].overhang);

  if ((nb_end - nb_start) == 1 && sum_abs_overhang < OVERHANG_MAX) {
    // apply correction
    res[0].genome_pos += res[0].overhang;
    res[1].genome_pos += res[1].overhang;
    res[0].brk = new_break0;
    res[1].brk = new_break1;
    res[0].aligns = true;
    res[1].aligns = true;
    aligns = true;

    bool inframe = false;
    if (res[0].frame >= 0 && res[1].frame >= 0 &&
        res[0].frame == res[1].frame &&
        (res[0].is_actually_the_start != res[1].is_actually_the_start)) {
      inframe = true;
    }
    res[0].inFrame = inframe;
    res[1].inFrame = inframe;
  } else {
    res[0].aligns = false;
    res[1].aligns = false;
    res[0].inFrame = false;
    res[1].inFrame = false;
  }

  return res;
}

static FinalRow format_positions(
    const std::vector<BreakHit>& x2,
    const std::unordered_map<std::string, std::string>& gene_to_strand
) {
  FinalRow out;
  if (x2.size() != 2) {
    out.contig_break = 0;
    out.chrom1 = out.chrom2 = "";
    out.base1 = out.base2 = 0;
    out.strand1 = out.strand2 = "";
    out.gap = std::numeric_limits<double>::quiet_NaN();
    out.rearrangement = false;
    out.aligns = false;
    out.inframe = false;
    out.fusion_genes = "";
    out.exon1 = out.exon2 = "";
    return out;
  }

  // order by is_actually_the_start decreasing TRUE first
  int a = (x2[0].is_actually_the_start ? 0 : 1);
  int b = 1 - a;

  const BreakHit& h1 = x2[a];
  const BreakHit& h2 = x2[b];

  out.chrom1 = h1.genome_chrom;
  out.chrom2 = h2.genome_chrom;
  out.base1 = h1.genome_pos;
  out.base2 = h2.genome_pos;

  {
    std::unordered_map<std::string, std::string>::const_iterator it = gene_to_strand.find(h1.gene_name);
    out.strand1 = (it == gene_to_strand.end() ? "" : it->second);
  }
  {
    std::unordered_map<std::string, std::string>::const_iterator it = gene_to_strand.find(h2.gene_name);
    out.strand2 = (it == gene_to_strand.end() ? "" : it->second);
  }

  out.gap = h1.gap;                 // kb
  out.rearrangement = h1.rearrangement;
  out.aligns = (h1.aligns && h2.aligns);
  out.inframe = h1.inFrame;

  out.contig_break = std::min(h1.brk, h2.brk);

  out.fusion_genes = h1.gene_name + "::" + h2.gene_name;
  out.exon1 = h1.exons;
  out.exon2 = h2.exons;
  return out;
}

static std::vector<std::string> read_single_column_list(const std::string& path) {
  std::ifstream in(path.c_str());
  if (!in) throw std::runtime_error("Failed to open: " + path);
  std::vector<std::string> out;
  std::string line;
  while (read_line(in, line)) {
    if (line.empty()) continue;
    std::vector<std::string> f = split_tsv(line);
    if (!f.empty()) out.push_back(f[0]);
  }
  return out;
}

static std::unordered_map<std::string, std::string> read_two_col_map_str(const std::string& path, int key_col, int val_col) {
  std::ifstream in(path.c_str());
  if (!in) throw std::runtime_error("Failed to open: " + path);
  std::unordered_map<std::string, std::string> m;
  std::string line;
  while (read_line(in, line)) {
    if (line.empty()) continue;
    std::vector<std::string> f = split_tsv(line);
    if ((int)f.size() <= std::max(key_col, val_col)) continue;
    m[f[key_col]] = f[val_col];
  }
  return m;
}

static std::unordered_map<std::string, long long> read_two_col_map_ll(const std::string& path, int val_col, int key_col) {
  // R: gtex_freq=as.numeric(col1); names=col2 => map fusion->freq
  std::ifstream in(path.c_str());
  if (!in) throw std::runtime_error("Failed to open: " + path);
  std::unordered_map<std::string, long long> m;
  std::string line;
  while (read_line(in, line)) {
    if (line.empty()) continue;
    std::vector<std::string> f = split_tsv(line);
    if ((int)f.size() <= std::max(val_col, key_col)) continue;
    long long val = to_ll(f[val_col], 0);
    m[f[key_col]] = val;
  }
  return m;
}

static std::unordered_map<std::string, double> read_gene_counts(const std::string& path) {
  std::ifstream in(path.c_str());
  if (!in) throw std::runtime_error("Failed to open gene_count_table_file: " + path);

  std::unordered_map<std::string, double> m;
  std::string line;
  while (read_line(in, line)) {
    if (line.empty()) continue;
    std::vector<std::string> f = split_tsv(line);
    if (f.size() < 2) continue;
    m[f[0]] = to_double(f[1], 0.0);
  }
  return m;
}

static std::string make_break_string(const FinalRow& r) {
  std::ostringstream oss;
  oss << r.chrom1 << r.base1 << ":" << r.chrom2 << r.base2;
  return oss.str();
}

static void write_output(const std::string& path, const std::vector<FinalRow>& rows) {
  std::ofstream out(path.c_str());
  if (!out) throw std::runtime_error("Failed to write output_file: " + path);

  // header: matches R's cand columns plus added ones
  out
    << "transcript\tspanning_pairs\tspanning_reads\t"
    << "contig_break\tchrom1\tbase1\tstrand1\tchrom2\tbase2\tstrand2\t"
    << "gap\trearrangement\taligns\tinframe\tfusion_genes\texon1\texon2\t"
    << "known_mitelman\tknown_cosmic\tcosmic_tier\tgtex_samples\t"
    << "geneCounts1\tgeneCounts2\tclassification\n";

  for (size_t i = 0; i < rows.size(); ++i) {
    const FinalRow& r = rows[i];
    out
      << r.transcript << "\t"
      << r.spanning_pairs << "\t"
      << r.spanning_reads << "\t"
      << r.contig_break << "\t"
      << r.chrom1 << "\t"
      << r.base1 << "\t"
      << r.strand1 << "\t"
      << r.chrom2 << "\t"
      << r.base2 << "\t"
      << r.strand2 << "\t";

    if (std::isnan(r.gap)) out << "NA";
    else out << r.gap;

    out << "\t"
      << (r.rearrangement ? "TRUE" : "FALSE") << "\t"
      << (r.aligns ? "TRUE" : "FALSE") << "\t"
      << (r.classification == "LowConfidence" ? "NA" : (r.inframe ? "TRUE" : "FALSE")) << "\t" 
      << r.fusion_genes << "\t"
      << r.exon1 << "\t"
      << r.exon2 << "\t"
      << r.known_mitelman << "\t"
      << r.known_cosmic << "\t"
      << r.cosmic_tier << "\t"
      << r.gtex_samples << "\t"
      << r.geneCounts1 << "\t"
      << r.geneCounts2 << "\t"
      << r.classification
      << "\n";
  }
}

int main(int argc, char** argv) {
  try {
    if (argc != 13) {
      std::cerr
        << "Usage:\n"
        << "  " << argv[0]
        << " <blat.psl> <fusion_info.reads> <gene_counts> <trans_table>"
        << " <mitelman> <cosmic> <cosmic_tier> <gtex>"
        << " <gapmin_bp> <exclude_csv> <MIN_REASSIGNMENT_BASE_DIFF> <output>\n";
      return 2;
    }

    const std::string blat_table_file = argv[1];
    const std::string fusion_info_file = argv[2];
    const std::string gene_count_table_file = argv[3];
    const std::string trans_table_file = argv[4];
    const std::string known_table_file_mitel = argv[5];
    const std::string known_table_file_cosmic = argv[6];
    const std::string known_table_file_cosmic_tier = argv[7];
    const std::string known_table_file_gtex = argv[8];

    const long long gapmin_bp = to_ll(argv[9], 0);
    const std::string exclude_csv = argv[10];
    const long long MIN_REASSIGNMENT_BASE_DIFF = to_ll(argv[11], 0);
    const std::string output_file = argv[12];

    std::cerr << "[INFO] Starting final fusion filtering\n";
    
    // Load inputs
    std::vector<FusionInfoRow> fusion_info = read_fusion_info(fusion_info_file);
    std::cerr << "[INFO] Loaded " << fusion_info.size() << " candidate fusion reads\n";
    
    std::vector<AnnoRow> transTable = read_annotation_table(trans_table_file);
    std::unordered_map<std::string, std::vector<AnnoRow> > trans_by_chr = split_annotation_by_chr(transTable);
    std::unordered_map<std::string, std::string> gene_to_strand = build_gene_to_strand(transTable);
    
    std::vector<BlatPslRow> blat = read_psl(blat_table_file);
    if (REMOVE_ALT) {
      std::vector<BlatPslRow> filtered;
      filtered.reserve(blat.size());
      for (size_t i = 0; i < blat.size(); ++i) {
        if (!contains(blat[i].tName, "_alt")) filtered.push_back(blat[i]);
      }
      blat.swap(filtered);
    }

    std::unordered_map<std::string, std::vector<int> > blat_index = build_blat_index(blat);

    // 1) get_break_pos for each fusion transcript
    std::cerr << "[INFO] Getting breakpoint positions \n";
    std::vector< std::vector<BreakHit> > genome_pos;
    genome_pos.reserve(fusion_info.size());
    for (size_t i = 0; i < fusion_info.size(); ++i) {
      genome_pos.push_back(get_break_pos_for_transcript(fusion_info[i], blat, blat_index));
    }

    // 2) check_gap
    std::cerr << "[INFO] Checking gap size \n";
    std::vector< std::vector<BreakHit> > new_genome_pos;
    new_genome_pos.reserve(genome_pos.size());
    for (size_t i = 0; i < genome_pos.size(); ++i) {
      new_genome_pos.push_back(check_gap_choose_pair(genome_pos[i], gapmin_bp));
    }

    // 3) frame info + exon boundary adjustment
    std::cerr << "[INFO] Refining breakpoints and checking frame \n";
    std::vector< std::vector<BreakHit> > new_new_genome_pos;
    new_new_genome_pos.reserve(new_genome_pos.size());
    for (size_t i = 0; i < new_genome_pos.size(); ++i) {
      if (new_genome_pos[i].empty()) {
        new_new_genome_pos.push_back(std::vector<BreakHit>());
      } else {
        new_new_genome_pos.push_back(get_frame_info_for_pair(new_genome_pos[i], trans_by_chr));
      }
    }

    // 4) format_positions => genome_info
    std::cerr << "[INFO] Formatting table \n";
    std::vector<FinalRow> result;
    result.reserve(fusion_info.size());

    for (size_t i = 0; i < fusion_info.size(); ++i) {
      FinalRow row;
      row.transcript = fusion_info[i].transcript;
      row.spanning_pairs = fusion_info[i].spanning_pairs_raw;
      row.spanning_reads = fusion_info[i].spanning_reads;

      FinalRow g = format_positions(new_new_genome_pos[i], gene_to_strand);

      row.contig_break = g.contig_break;
      row.chrom1 = g.chrom1; row.base1 = g.base1; row.strand1 = g.strand1;
      row.chrom2 = g.chrom2; row.base2 = g.base2; row.strand2 = g.strand2;
      row.gap = g.gap;
      row.rearrangement = g.rearrangement;
      row.aligns = g.aligns;
      row.inframe = g.inframe;
      row.fusion_genes = g.fusion_genes;
      row.exon1 = g.exon1; row.exon2 = g.exon2;

      result.push_back(row);
    }

    // If no reads passed genome alignment filters (all chrom1 empty), write empty and exit
    bool any_genome = false;
    for (size_t i = 0; i < result.size(); ++i) {
      if (!result[i].chrom1.empty()) { any_genome = true; break; }
    }
    if (!any_genome) {
      std::ofstream out(output_file.c_str()); // create empty file
      return 0;
    }

    // reorder so aligned breaks first
    std::sort(result.begin(), result.end(), [](const FinalRow& a, const FinalRow& b){
      return (a.aligns > b.aligns);
    });

    // Remove double counts: duplicated (fusion_genes, transcript)
    {
      std::set< std::pair<std::string,std::string> > seen;
      std::vector<FinalRow> tmp;
      tmp.reserve(result.size());
      for (size_t i = 0; i < result.size(); ++i) {
        std::pair<std::string,std::string> key(result[i].fusion_genes, result[i].transcript);
        if (seen.insert(key).second) tmp.push_back(result[i]);
      }
      result.swap(tmp);
    }

    // Group by breakpoint (chrom1/base1 : chrom2/base2) and merge_result
    std::unordered_map<std::string, std::vector<FinalRow> > groups;
    for (size_t i = 0; i < result.size(); ++i) {
      std::string k = make_break_string(result[i]);
      groups[k].push_back(result[i]);
    }

    std::vector<FinalRow> merged;
    merged.reserve(groups.size());
    for (std::unordered_map<std::string, std::vector<FinalRow> >::iterator it = groups.begin(); it != groups.end(); ++it) {
      std::vector<FinalRow>& v = it->second;
      if (v.empty()) continue;

      bool is_short = true;
      for (size_t i = 0; i < v.size(); ++i) if (v[i].spanning_pairs != "-") { is_short = false; break; }

      // convert spanning_pairs "-" to 0 for ranking
      std::vector<long long> sp(v.size(), 0);
      for (size_t i = 0; i < v.size(); ++i) {
        if (v[i].spanning_pairs == "-") sp[i] = 0;
        else sp[i] = to_ll(v[i].spanning_pairs, 0);
      }

      // sort by spanning_pairs desc, then fusion_genes asc (as per R code)
      std::vector<size_t> ord(v.size());
      for (size_t i = 0; i < ord.size(); ++i) ord[i] = i;
      std::sort(ord.begin(), ord.end(), [&](size_t a, size_t b){
        if (sp[a] != sp[b]) return sp[a] > sp[b];
        return v[a].fusion_genes < v[b].fusion_genes;
      });

      FinalRow rep = v[ord[0]];
      long long max_sp = 0;
      long long sum_reads = 0;
      for (size_t i = 0; i < v.size(); ++i) {
        max_sp = std::max(max_sp, sp[i]);
        sum_reads += v[i].spanning_reads;
      }
      rep.spanning_reads = sum_reads;
      if (is_short) rep.spanning_pairs = "-";
      else {
        std::ostringstream oss; oss << max_sp;
        rep.spanning_pairs = oss.str();
      }
      merged.push_back(rep);
    }

    // cand = those with rearrangement defined (in R: !is.na(rearrangement))
    // Here, if chrom1 empty then it's "NA-like", so drop those.
    std::vector<FinalRow> cand;
    cand.reserve(merged.size());
    for (size_t i = 0; i < merged.size(); ++i) {
      if (!merged[i].chrom1.empty()) cand.push_back(merged[i]);
    }

    std::cerr << "[INFO] Checking for fusions in databases \n";
    // DB annotations
    {
      std::vector<std::string> mit = read_single_column_list(known_table_file_mitel);
      std::set<std::string> mit_set(mit.begin(), mit.end());

      std::vector<std::string> cos = read_single_column_list(known_table_file_cosmic);
      std::set<std::string> cos_set(cos.begin(), cos.end());

      std::unordered_map<std::string, std::string> cosmic_tier = read_two_col_map_str(known_table_file_cosmic_tier, 0, 1);
      std::unordered_map<std::string, long long> gtex = read_two_col_map_ll(known_table_file_gtex, 0, 1);

      for (size_t i = 0; i < cand.size(); ++i) {
        if (mit_set.count(cand[i].fusion_genes)) cand[i].known_mitelman = "Yes";
        if (cos_set.count(cand[i].fusion_genes)) cand[i].known_cosmic = "Yes";

        std::vector<std::string> gs = split(cand[i].fusion_genes, ':', true);
        // split by "::" more safely:
        std::vector<std::string> gg = split(cand[i].fusion_genes, ':', true); // placeholder
        // do exact:
        size_t p = cand[i].fusion_genes.find("::");
        std::string g1 = (p == std::string::npos) ? cand[i].fusion_genes : cand[i].fusion_genes.substr(0, p);
        std::string g2 = (p == std::string::npos) ? "" : cand[i].fusion_genes.substr(p + 2);

        std::string t1 = "-";
        std::string t2 = "-";
        {
          std::unordered_map<std::string, std::string>::const_iterator it = cosmic_tier.find(g1);
          if (it != cosmic_tier.end()) t1 = it->second;
        }
        {
          std::unordered_map<std::string, std::string>::const_iterator it = cosmic_tier.find(g2);
          if (it != cosmic_tier.end()) t2 = it->second;
        }
        cand[i].cosmic_tier = t1 + "::" + t2;

        std::unordered_map<std::string, long long>::const_iterator itg = gtex.find(cand[i].fusion_genes);
        cand[i].gtex_samples = (itg == gtex.end()) ? 0 : itg->second;
      }
    }

    // remove chrM
    if (REMOVE_CHRM) {
      std::vector<FinalRow> tmp;
      tmp.reserve(cand.size());
      for (size_t i = 0; i < cand.size(); ++i) {
        if (cand[i].chrom1 == "chrM" || cand[i].chrom2 == "chrM") continue;
        tmp.push_back(cand[i]);
      }
      cand.swap(tmp);
    }

    std::cerr << "[INFO] Assigning confidence levels \n";
    // Reassign Low Confidence breakpoints (long read noise handling)

    if (MIN_REASSIGNMENT_BASE_DIFF > 0) {

      std::cerr << "[INFO] Reassigning low-confidence breakpoints\n";

      // Sort so aligned + high-read rows are first
      // (matches R: order by aligns, then spanning_reads)
      std::sort(cand.begin(), cand.end(),
		[](const FinalRow& a, const FinalRow& b) {
		  if (a.aligns != b.aligns)
		    return a.aligns > b.aligns;
		  return a.spanning_reads > b.spanning_reads;
		}
		);

      // Group rows by fusion_genes
      std::unordered_map<std::string, std::vector<int>> groups;
      for (size_t i = 0; i < cand.size(); ++i) {
	groups[cand[i].fusion_genes].push_back((int)i);
      }

      // Process each fusion independently
      for (auto& kv : groups) {

	std::vector<int>& g = kv.second;
	if (g.size() <= 1) continue;

	// Identify aligned breakpoints (anchors)
	std::vector<int> anchors;
	for (int idx : g) {
	  if (cand[idx].aligns)
	    anchors.push_back(idx);
	}

	// Collect non-aligned candidates
	std::vector<int> to_correct;
	for (int idx : g) {
	  if (!cand[idx].aligns && cand[idx].spanning_reads > 0)
	    to_correct.push_back(idx);
	}

	if (to_correct.empty()) continue;

	// IMPORTANT:
	// Mimic R's rev(to_correct) behaviour.
	// Process weakest breakpoints first so they do not
	// become sinks for stronger ones.
	std::sort(to_correct.begin(), to_correct.end(),
		  [&](int a, int b) {

		    // lowest spanning_reads first
		    if (cand[a].spanning_reads != cand[b].spanning_reads)
		      return cand[a].spanning_reads < cand[b].spanning_reads;

		    // deterministic tie-breaking
		    if (cand[a].base1 != cand[b].base1)
		      return cand[a].base1 < cand[b].base1;
		    return cand[a].base2 < cand[b].base2;
		  }
		  );

	// Reassign
	for (int idx : to_correct) {

	  // might already have been reassigned
	  if (cand[idx].spanning_reads == 0)
	    continue;

	  int best_target = -1;
	  double best_dist = std::numeric_limits<double>::infinity();

	  // Prefer anchors if they exist (this mirrors R behaviour)
	  const std::vector<int>& targets =
	    anchors.empty() ? g : anchors;

	  for (int t : targets) {

	    if (t == idx) continue;
	    if (cand[t].spanning_reads == 0) continue;

	    double dx = (double)cand[idx].base1 - cand[t].base1;
	    double dy = (double)cand[idx].base2 - cand[t].base2;
	    double d  = std::sqrt(dx*dx + dy*dy);

	    // Deterministic tie-breaking:
	    // 1) smaller distance
	    // 2) higher spanning_reads
	    if (d < best_dist ||
		(std::abs(d - best_dist) < 1e-9 &&
		 best_target >= 0 &&
		 cand[t].spanning_reads > cand[best_target].spanning_reads)) {

	      best_dist = d;
	      best_target = t;
	    }
	  }

	  // Reassign if within threshold
	  if (best_target >= 0 &&
	      best_dist < (double)MIN_REASSIGNMENT_BASE_DIFF) {

	    cand[best_target].spanning_reads += cand[idx].spanning_reads;
	    cand[idx].spanning_reads = 0;
	  }
	}
      }

      // Remove reassigned rows
      std::vector<FinalRow> filtered;
      filtered.reserve(cand.size());

      for (const auto& r : cand) {
	if (r.spanning_reads > 0)
	  filtered.push_back(r);
      }

      cand.swap(filtered);
    }


    // Add gene-level counts
    std::unordered_map<std::string, double> geneCounts = read_gene_counts(gene_count_table_file);
    for (size_t i = 0; i < cand.size(); ++i) {
      size_t p = cand[i].fusion_genes.find("::");
      std::string g1 = (p == std::string::npos) ? cand[i].fusion_genes : cand[i].fusion_genes.substr(0, p);
      std::string g2 = (p == std::string::npos) ? "" : cand[i].fusion_genes.substr(p + 2);

      std::unordered_map<std::string,double>::const_iterator it1 = geneCounts.find(g1);
      std::unordered_map<std::string,double>::const_iterator it2 = geneCounts.find(g2);
      cand[i].geneCounts1 = (it1 == geneCounts.end()) ? 0.0 : it1->second;
      cand[i].geneCounts2 = (it2 == geneCounts.end()) ? 0.0 : it2->second;
    }

    // Filter by gap (kb): cand$gap > (gapmin/1000)
    const double gapmin_kb = (double)gapmin_bp / 1000.0;
    {
      std::vector<FinalRow> tmp;
      tmp.reserve(cand.size());
      for (size_t i = 0; i < cand.size(); ++i) {
        if (std::isnan(cand[i].gap)) continue;
        if (cand[i].gap > gapmin_kb) tmp.push_back(cand[i]);
      }
      cand.swap(tmp);
    }

    // Classification logic
    // spanP = spanning_pairs > 0 (numeric); single if no spanP anywhere
    bool any_spanP = false;
    std::vector<long long> sp_pairs_num(cand.size(), 0);
    for (size_t i = 0; i < cand.size(); ++i) {
      long long v = 0;
      if (cand[i].spanning_pairs != "-") v = to_ll(cand[i].spanning_pairs, 0);
      sp_pairs_num[i] = v;
      if (v > 0) any_spanP = true;
    }
    bool single = !any_spanP;

    for (size_t i = 0; i < cand.size(); ++i) {
      bool spanP = sp_pairs_num[i] > 0;
      bool spanR = cand[i].spanning_reads > 0;
      bool spanT = spanR && ((cand[i].spanning_reads + sp_pairs_num[i]) >= MIN_LOW_SPANNING_READS);

      cand[i].classification = "NoSupport";
      if ((spanP || single) && spanT) cand[i].classification = "LowConfidence";
      if (cand[i].aligns && spanR) cand[i].classification = "MediumConfidence";
      if (cand[i].aligns && (spanP || single) && spanT) cand[i].classification = "HighConfidence";

      // special cases
      if (cand[i].aligns && !spanP && cand[i].spanning_reads == 1) cand[i].classification = "PotentialTransSplicing";
      if ((cand[i].gap < (double)REGGAP) && (spanP || spanR) && !cand[i].rearrangement) cand[i].classification = "PotentialReadThrough";

      // downgrade HC calls if recurrent in GTex (20+)
      if (cand[i].classification == "HighConfidence" && cand[i].gtex_samples >= 20) {
        cand[i].classification = "PotentialTransSplicing";
        if (cand[i].gap < (double)REGGAP && !cand[i].rearrangement) cand[i].classification = "PotentialReadThrough";
      }

      // reclass anything with a cosmic fusion as high confidence (if not NoSupport)
      if (cand[i].known_cosmic == "Yes" && cand[i].classification != "NoSupport") cand[i].classification = "HighConfidence";
    }

    // exclude list
    std::set<std::string> exclude;
    {
      std::vector<std::string> ex = split(exclude_csv, ',', true);
      for (size_t i = 0; i < ex.size(); ++i) if (!ex[i].empty()) exclude.insert(ex[i]);
    }
    if (!exclude.empty()) {
      std::vector<FinalRow> tmp;
      tmp.reserve(cand.size());
      for (size_t i = 0; i < cand.size(); ++i) {
        if (exclude.count(cand[i].classification)) continue;
        tmp.push_back(cand[i]);
      }
      cand.swap(tmp);
    }

    std::cerr << "[INFO] Finally... writing out table\n";
    // Write
    write_output(output_file, cand);
    return 0;

  } catch (const std::exception& e) {
    std::cerr << "ERROR: " << e.what() << "\n";
    return 1;
  }
}
